---
title: "Leaflet App"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(leaflet)
library(maps)
```

```{r}
data <- read.csv("earthquake_all.csv")
data <- data[!is.na(data$mag) & data$mag > 0 & data$mag < 8,]
```

# create basic leaflet graph (Created on September 1, 2018)
```{r}
mapCountries = map("world", fill = TRUE, plot = FALSE)

# Create a color palette with handmade bins.
mybins=seq(0, 8, by=1)
mypalette = colorBin(palette="RdYlGn", domain=data$mag, na.color="transparent", bins=mybins, reverse=TRUE)

# Prepar the text for the tooltip:
mytext=paste("Depth: ", data$depth, "<br/>", "Stations: ", data$stations, "<br/>", "Magnitude: ", data$mag, sep="") %>%
  lapply(htmltools::HTML)

# Final Map
leaflet(data = mapCountries) %>% addTiles() %>%
    addProviderTiles("NASAGIBS.ViirsEarthAtNight2012") %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE, label=paste(mapCountries$names)) %>%
  setView(lat=-0, lng=0 , zoom=2) %>%
  addCircleMarkers(data$longitude, data$latitude, 
    fillColor = ~mypalette(data$mag), 
    fillOpacity = 0.7, 
    color="white", radius=data$mag^1.3, stroke=FALSE,
    label = mytext,
    labelOptions = labelOptions( style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "13px", direction = "auto")
  ) %>%
  addLegend( pal=mypalette, values=~data$mag, opacity=0.9, title = "Magnitude", position = "bottomright" )

```
